### PR TITLE
added dedupe with tests

### PR DESCRIPTION
**Pull request by GoodGuyGoose**
Created dedupe transformer that removes duplicates from an array.  It accepts "path" as an optional argument.  This allows the removal of duplicates based on an embedded value inside objects in the array.  It also handles removing duplicates that are simple types, from the arrays.

### CODE REVIEW

**Review by kjellmorten — COMMENTED** [review]
Great work!

We talked about having a test with a combination of objects and plain values. Would you please add that too?

**Comment by GoodGuyGoose** [comment]
Pushed the test you wanted.  Also added handling of undefined. They will now be removed rather than being kept as a unique value! Looking forward to your excellent review commentary! [insert_optimistic_emoji_here]

**Review by kjellmorten — COMMENTED** [review]
Perfect, but ... 😏 

It seems your last commit removed two tests that you had in your first commit:
- should return empty array if array is empty
- should return data if data is not an array

I think you should add those back, as they are important to cover all cases.

[big_smile_with_thumbs_up_and_fireworks_in_the_background]

**Comment by GoodGuyGoose** [comment]
Not sure how they escaped but they have been wrangled back to where they belong

**Review by kjellmorten — APPROVED** [review]
Splendid!

**Pull request merged**
